import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  textCenter: { textAlign: "center" },
  leaveStatusSubcontainer: {
    flex: 1,
    padding: 10,
    alignContent: "center",
    textAlignVertical: "center",
  },
  leaveStatusContainer: {
    flex: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    backgroundColor: "#f0f0f0",
    borderColor: "#a6cfd8",
  },
  todate: { textAlign: "center" },
  toLeaveSubContainer: {
    flex: 0.5,
    padding: 10,
    alignContent: "center",
    textAlignVertical: "center",
  },
  from: {
    textAlign: "center",
    textAlignVertical: "center",
  },
  leaveFromSubContainer: {
    padding: 10,
    flex: 0.5,
    alignContent: "center",
    textAlignVertical: "center",
  },
  leaveFromContainer: {
    flex: 1,
    flexDirection: "row",
    height: 30,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "#a6cfd8",
  },
  leaveType: {
    color: "white",
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "bold",
  },
  leaveStyleContainer: {
    padding: 10,
    flex: 1,
    alignContent: "center",
    textAlignVertical: "center",
  },
  itemContainer: {
    flex: 1,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#a6cfd8",
    marginTop: 10,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: "#a6cfd8",
  },
  leaveRequestsTitle: {
    color: "#061f5d",
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
  },
  tableRightTitle: {
    flex: 0.5,

    alignContent: "center",
    fontWeight: "bold",
    padding: 10,
    textAlignVertical: "center",
  },
  tableHeader: {
    padding: 10,
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "bold",
    color: "white",
  },
  tableHeaderItem: {
    flex: 0.5,
    alignContent: "center",
    textAlignVertical: "center",
  },
  tableHeaderConatiner: {
    flex: 1,
    flexDirection: "row",
    height: 40,
    borderWidth: 1,
    borderColor: "#a6cfd8",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: "#a6cfd8",
  },
  leaveSummaryTitle: {
    color: "#061f5d",
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
  },
  bankholidayContainer: {
    width: 200,
    flexDirection: "row",
    alignItems: "center",
  },
  buttonText: { color: "white" },
  myLeaveButtonConatiner: {
    width: 200,
    flexDirection: "row",
    alignItems: "center",
  },
  myLeaveButton: { flex: 0.5, marginLeft: 12 },
  topBarContainer: {
    flex: 1,
    paddingRight: 15,
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 10,
  },
  scrollViewContentContainer: { paddingVertical: 10 },
  scrollView: { width: "100%" },
  indicator: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    height: 20,
  },
  container: {
    flex: 1,
    height: "100%",
    flexDirection: "column",
    flexWrap: "wrap",
    backgroundColor: "mintcream",
  },
  button: {
    alignItems: "center",
    height: 50,
  },
  openButton: {
    borderRadius: 5,
    padding: 1,
    elevation: 2,
    textAlign: "right",
  },
  leaveSummaryBox: {
    width: "100%",
    height: "auto",
    padding: 5,
    justifyContent: "flex-end",
    fontSize: 20,
  },
  boxTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black",
    textAlign: "center",
  },
});
