import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  itemContainer: {
    flex: 1,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#a6cfd8",
    marginTop: 10,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: "#a6cfd8",
  },
  leaveStatusSubcontainer: {
    flex: 1,
    padding: 10,
    alignContent: "center",
    textAlignVertical: "center",
  },
  leaveStatusContainer: {
    flex: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    backgroundColor: "#f0f0f0",
    borderColor: "#a6cfd8",
  },
  todate: { textAlign: "center" },
  toLeaveSubContainer: {
    flex: 0.5,
    padding: 10,
    alignContent: "center",
    textAlignVertical: "center",
  },
  from: {
    textAlign: "center",
    textAlignVertical: "center",
  },
  leaveFromSubContainer: {
    padding: 10,
    flex: 1,
    alignContent: "center",
    textAlignVertical: "center",
  },
  leaveFromContainer: {
    flex: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "#a6cfd8",
  },
  leaveType: {
    color: "white",
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "bold",
  },
  leaveStyleContainer: {
    padding: 10,
    flex: 1,
    alignContent: "center",
    textAlignVertical: "center",
  },
  totalLeave: {
    padding: 5,
    flex: 0.5,
    alignContent: "center",
    textAlignVertical: "center",
  },
  leaveEntitlementContainer: {
    flex: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "#a6cfd8",
  },
  leaveEntitlementSubContainer: {
    flex: 1,
    alignContent: "center",
    textAlignVertical: "center",
    flexDirection: "row",
    borderColor: "#a6cfd8",
    borderRightWidth: 1,
    flexWrap: "wrap",
  },
  leaveTypeText: {
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 4,
    textAlign: "left",
    textAlignVertical: "center",
  },
  textCenter: {
    textAlign: "center",
  },
});
